name = "Arknights Craft"
author = "shotata"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb5f80c3ae307ec2c3ce940195e228f2f5bbb04b14639eb5449a6e88bf2fce00"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
