name = "Arknights Craft"
author = "shotata"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3fbec765243141ed18b512f92f44d66096429feeca5e637226f62d140c4d8ca"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
