name = "Arknights Craft"
author = "shotata"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dc7e50b8e96e5564e34de08aed2c463c6b5a0b75febb629e386b2d24b4596fe"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
